version: "2"
services:
  sygal-import-ws:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: http://10.14.128.99:3128
        https_proxy: http://10.14.128.99:3128
        no_proxy: localhost,127.0.0.1,.unicaen.fr
    ports:
     - "8080:8080"
    volumes:
     - .:/var/www
    network_mode: bridge
    dns: 10.14.128.125
    dns_search: unicaen.fr
