version: "2"

services:
  sygal-import-ws:
#    image: sygal-import-ws-image-php7.3
    build:
      context: .
      args:
        - PHP_VERSION=7.3
    container_name: sygal-import-ws-container-php7.3
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
      - "8443:443"
    volumes:
      - .:/app
      - /tmp:/tmp
    working_dir: /app
    network_mode: bridge