version: "2"

services:
  sygal-import-ws:
    container_name: sygal-import-ws-container
    build:
      context: .
      dockerfile: Dockerfile.php7.dev
    ports:
     - "8080:8080"
    volumes:
     - .:/sygal-import-ws
    network_mode: bridge
    dns_search: unicaen.fr
