version: "2"

services:
  sygal-import-ws:
    image: sygal-import-ws-image-php7.0
    container_name: sygal-import-ws-container-php7.0
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
      - "8443:443"
    volumes:
      - .:/app
      - /tmp:/tmp
    working_dir: /app
    network_mode: bridge