version: "2"

services:
  sygal-import-ws:
#    image: registre.unicaen.fr:5000/sygal-import-ws-image-php8.0
    image: sygal-import-ws-image-php8.0
#    build:
#      context: .
#      args:
#        - PHP_VERSION=8.0
    container_name: sygal-import-ws-container-php8.0
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
      - "8443:443"
    volumes:
      - .:/app
      - /tmp:/tmp
      - ~/.config/composer/:/root/.config/composer/:ro
    working_dir: /app
    network_mode: bridge