--
-- Web Service d'import de données pour SyGAL
-- ------------------------------------------
--
-- Tables à créer par l'établissement.
--

--
-- NB : Seule la table `SYGAL_DOCTORANT_V3` existe en version "V3", c'est normal.
--      Les autres tables restent en version "V2".
--

create table SYGAL_ACTEUR_V2
(
    SOURCE_INSERT_DATE DATE default sysdate,
    TEM_RAP_RECU VARCHAR2(1),
    TEM_HAB_RCH_PER VARCHAR2(1) not null,
    LIB_CPS VARCHAR2(40),
    COD_CPS VARCHAR2(10),
    LIB_PAY_ETB VARCHAR2(40),
    COD_PAY_ETB VARCHAR2(3),
    ACTEUR_ETABLISSEMENT_ID VARCHAR2(8),
    INDIVIDU_ID VARCHAR2(4000),
    COD_PER NUMBER(8),
    LIB_ROJ_COMPL VARCHAR2(21),
    COD_ROJ_COMPL VARCHAR2(1 char),
    ROLE_ID CHAR,
    THESE_ID NUMBER(8),
    SOURCE_ID CHAR(6),
    SOURCE_CODE VARCHAR2(104),
    ID VARCHAR2(104)
)
/

create table SYGAL_DOCTORANT_V3 -- V3, oui c'est normal !
(
    SOURCE_INSERT_DATE DATE default sysdate,
    INE VARCHAR2(12),
    CODE_APPRENANT_IN_SOURCE VARCHAR2(64),
    INDIVIDU_ID NUMBER(8),
    ID NUMBER(8),
    SOURCE_ID CHAR(6),
    SOURCE_CODE NUMBER(8)
)
/

create table SYGAL_ECOLE_DOCT_V2
(
    SOURCE_INSERT_DATE DATE default sysdate,
    SOURCE_CODE VARCHAR2(4),
    STRUCTURE_ID VARCHAR2(4),
    SOURCE_ID CHAR(6),
    ID VARCHAR2(4)
)
/

create table SYGAL_ETABLISSEMENT_V2
(
    SOURCE_INSERT_DATE DATE default sysdate,
    ID VARCHAR2(8),
    SOURCE_ID CHAR(6),
    CODE VARCHAR2(8),
    STRUCTURE_ID VARCHAR2(8),
    SOURCE_CODE VARCHAR2(8)
)
/

create table SYGAL_FINANCEMENT_V2
(
    DATE_FIN_FINANCEMENT DATE,
    QUOTITE_FINANCEMENT NUMBER(3),
    ORIGINE_FINANCEMENT_ID VARCHAR2(2),
    CODE_TYPE_FINANCEMENT VARCHAR2(1),
    THESE_ID NUMBER(8) not null,
    SOURCE_CODE NUMBER,
    SOURCE_INSERT_DATE DATE default sysdate,
    DATE_DEBUT_FINANCEMENT DATE,
    COMPLEMENT_FINANCEMENT VARCHAR2(4000),
    LIBELLE_TYPE_FINANCEMENT VARCHAR2(40),
    ANNEE_ID VARCHAR2(4),
    SOURCE_ID CHAR(6),
    ID NUMBER
)
/

create table SYGAL_INDIVIDU_V2
(
    LIB_NAT VARCHAR2(40),
    DATE_NAI_IND DATE,
    LIB_PR3_IND VARCHAR2(20),
    LIB_PR1_IND VARCHAR2(20),
    LIB_NOM_PAT_IND VARCHAR2(40),
    SUPANN_ID VARCHAR2(4000),
    TYPE VARCHAR2(9),
    SOURCE_CODE VARCHAR2(4000),
    SOURCE_INSERT_DATE DATE default sysdate,
    COD_PAY_NAT VARCHAR2(3),
    EMAIL VARCHAR2(4000),
    LIB_PR2_IND VARCHAR2(20),
    LIB_NOM_USU_IND VARCHAR2(40),
    CIV VARCHAR2(5),
    ID VARCHAR2(4000),
    SOURCE_ID CHAR(6)
)
/

create table SYGAL_ORIGINE_FINANCEMENT_V2
(
    LIB_OFI VARCHAR2(40),
    COD_OFI CHAR(2),
    ID CHAR(2),
    SOURCE_INSERT_DATE DATE default sysdate,
    LIC_OFI VARCHAR2(10),
    SOURCE_ID CHAR(6),
    SOURCE_CODE CHAR(2)
)
/

create table SYGAL_ROLE_V2
(
    LIC_ROJ VARCHAR2(10),
    ID CHAR,
    SOURCE_CODE CHAR,
    SOURCE_INSERT_DATE DATE default sysdate,
    LIB_ROJ VARCHAR2(21),
    SOURCE_ID CHAR(6)
)
/

create table SYGAL_STRUCTURE_V2
(
    SIGLE VARCHAR2(25),
    TYPE_STRUCTURE_ID VARCHAR2(15),
    SOURCE_ID CHAR(6),
    SOURCE_CODE VARCHAR2(10),
    LIBELLE_PAYS VARCHAR2(40),
    CODE_PAYS VARCHAR2(3),
    ID VARCHAR2(10),
    SOURCE_INSERT_DATE DATE default sysdate,
    LIBELLE VARCHAR2(100)
)
/

create table SYGAL_THESE_V2
(
    SOURCE_INSERT_DATE DATE default sysdate,
    CORRECTION_POSSIBLE VARCHAR2(11),
    DAT_SOU_THS DATE,
    TEM_SOU_AUT_THS VARCHAR2(1),
    LIB_PAY VARCHAR2(40),
    ECOLE_DOCT_ID VARCHAR2(4),
    COD_LNG VARCHAR2(4),
    LIB_INT1_DIS VARCHAR2(200),
    DAT_FIN_CFD_THS DATE,
    DAT_PREV_SOU DATE,
    TEM_AVENANT VARCHAR2(1),
    SOURCE_ID CHAR(6),
    SOURCE_CODE NUMBER(8) not null,
    ID NUMBER(8) not null,
    UNITE_RECH_ID VARCHAR2(10),
    DAT_ABANDON DATE,
    CORRECTION_EFFECTUEE VARCHAR2(1),
    COD_DIS NUMBER(7),
    ETA_RPD_THS VARCHAR2(1),
    COD_NEG_TRE VARCHAR2(1),
    LIB_ETB_COT VARCHAR2(120),
    DAT_DEB_THS DATE,
    LIB_THS VARCHAR2(800),
    DOCTORANT_ID NUMBER(8),
    ETA_THS VARCHAR2(1),
    DAT_TRANSFERT_DEP DATE,
    DAT_AUT_SOU_THS DATE
)
/

create table SYGAL_THESE_ANNEE_UNIV_V2
(
    ID VARCHAR2(45),
    SOURCE_ID CHAR(6),
    ANNEE_UNIV VARCHAR2(4) not null,
    THESE_ID NUMBER(8) not null,
    SOURCE_INSERT_DATE DATE default sysdate,
    SOURCE_CODE VARCHAR2(45)
)
/

create table SYGAL_TITRE_ACCES_V2
(
    CODE_DEPT_TITRE_ACCES VARCHAR2(100),
    ID NUMBER(8) not null,
    SOURCE_CODE NUMBER(8) not null,
    SOURCE_INSERT_DATE DATE default sysdate,
    TITRE_ACCES_INTERNE_EXTERNE VARCHAR2(1),
    TYPE_ETB_TITRE_ACCES VARCHAR2(40),
    LIBELLE_TITRE_ACCES VARCHAR2(120),
    CODE_PAYS_TITRE_ACCES VARCHAR2(3),
    THESE_ID NUMBER(8) not null,
    LIBELLE_ETB_TITRE_ACCES VARCHAR2(100),
    SOURCE_ID CHAR(6)
)
/

create table SYGAL_UNITE_RECH_V2
(
    ID VARCHAR2(10) not null,
    SOURCE_ID CHAR(6),
    SOURCE_INSERT_DATE DATE default sysdate,
    SOURCE_CODE VARCHAR2(10) not null,
    STRUCTURE_ID VARCHAR2(10) not null
)
/

create table SYGAL_VARIABLE_V2
(
    PAR_VAP VARCHAR2(100),
    ID VARCHAR2(20),
    DATE_FIN_VALIDITE DATE,
    SOURCE_ID CHAR(6),
    DATE_DEB_VALIDITE DATE,
    SOURCE_CODE VARCHAR2(20),
    COD_VAP VARCHAR2(20),
    LIB_VAP VARCHAR2(47),
    SOURCE_INSERT_DATE DATE default sysdate
)
/


